version: '3'

services:
  invest-tests:
    image: 'romanew/invest:latest-tests'
    container_name: invest-tests
    environment:
      - tinkoff.is-token-sandbox=false
      - tinkoff.token=${TINKOFF_TOKEN}